### ISSUE TITLE
ApplangaSwiftUI Framework String interpolation error

### ISSUE THREAD

**Issue by haurimtonMartin** [applanga/sdk-swiftui#1]
## Description

After adding SwiftUI with SPM and running an existing project, string interpolation is converting the `\(value)` to `%@`.

## Steps

1. Add ApplangaSwiftUI package using SPM
2. Add ApplangaSwiftUI library to target
3. Run existing project and interpolated strings print `%@` instead of the string value

## Example

- Input
`"This is a test string with interpolation \(value)"`

- Output
`This is a test string with interpolation %@`

**Comment by ChristianStanke** [comment]
Thanks for the report! We'll be looking into it

**Comment by simonb-applanga** [comment]
@haurimtonMartin could you try to test with the latest release 2.0.170

**Comment by haurimtonMartin** [comment]
@simonb-applanga sorry for the delay, I just tested the latest release and it seems the issue was fixed, thank you all for your help.
